apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  type: ClusterIP  # Internal cluster communication only
  selector:
    app: service-1
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070