name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker to GCR
      run: |
        gcloud auth configure-docker

    - name: Build Docker Image
      run: |
        docker build --no-cache -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sliit-ctse:latest .

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sliit-ctse:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ctse-assignment --zone asia-south1-c --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
